#!/usr/bin/env python3

"""Generate regression JSON reports, a markdown table, and two SVG charts."""

from __future__ import annotations

import argparse
import html
import json
import math
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Mapping, Sequence

# Version labels accepted from the local git-bug bridge.
REGRESSION_LABEL_PATTERN: re.Pattern[str] = re.compile(r"^regression in (\d+(?:\.\d+)+)$")
# Version-shaped strings accepted as milestones.
VERSION_PATTERN: re.Pattern[str] = re.compile(r"^\d+(?:\.\d+)+$")
# GitHub issue URLs used to recover issue numbers from bridge metadata.
GITHUB_ISSUE_URL_PATTERN: re.Pattern[str] = re.compile(r"/issues/(\d+)$")

# This palette is "generated by https://gka.github.io/palettes/#/25|d|488f31,ffe692|ffe692,de425b|1|1".
VERSION_COLORS: list[str] = [
    "#488f31",
    "#599639",
    "#699e41",
    "#78a549",
    "#87ac51",
    "#96b459",
    "#a5bb61",
    "#b4c269",
    "#c3c971",
    "#d2d079",
    "#e1d881",
    "#f0df8a",
    "#ffe692",
    "#fed98d",
    "#fccd89",
    "#fac084",
    "#f8b47f",
    "#f5a77b",
    "#f39a76",
    "#f08d71",
    "#ed7f6d",
    "#e97268",
    "#e66364",
    "#e2535f",
    "#de425b",
]


@dataclass(frozen=True)
class Config:
    """Command-line configuration for the regression chart tool."""

    # repo_root is the Git repository that contains the local `.git/git-bug` bridge data.
    repo_root: Path
    # out_dir is the directory in which JSON, markdown, and SVG outputs are written.
    out_dir: Path
    # owner is the GitHub repository owner used for milestone lookups.
    owner: str
    # repo is the GitHub repository name used for milestone lookups.
    repo: str
    # chart_only requests SVG regeneration from existing JSON data instead of recomputing it.
    chart_only: bool


@dataclass(frozen=True)
class GitBugIssue:
    """Subset of `git bug bug --format json` consumed by this program."""

    # human_id is git-bug's short, human-friendly identifier for the issue.
    human_id: str
    # status is the current issue state as exposed by git-bug, typically "open" or "closed".
    status: str
    # labels is the issue's current label set.
    labels: list[str]
    # title is the issue title.
    title: str
    # metadata stores bridge-specific values such as the original GitHub issue URL.
    metadata: dict[str, str]

    @classmethod
    def from_json_dict(cls, data: Mapping[str, Any]) -> GitBugIssue:
        """Build a GitBugIssue from decoded JSON data.

        Args:
            data: A mapping decoded from `git bug bug --format json`.

        Returns:
            A typed GitBugIssue instance.
        """

        labels_raw: Any = data.get("labels", [])
        metadata_raw: Any = data.get("metadata", {})
        labels: list[str] = [str(label) for label in labels_raw or []]
        metadata: dict[str, str] = {
            str(key): str(value) for key, value in (metadata_raw or {}).items()
        }
        return cls(
            human_id=str(data.get("human_id", "")),
            status=str(data.get("status", "")),
            labels=labels,
            title=str(data.get("title", "")),
            metadata=metadata,
        )


@dataclass(frozen=True)
class RegressionIssue:
    """Normalized regression issue used for aggregation and rendering."""

    # issue_number is the original GitHub issue number recovered from bridge metadata.
    issue_number: int
    # human_id is git-bug's short identifier for the same issue.
    human_id: str
    # title is the issue title.
    title: str
    # url is the original GitHub issue URL.
    url: str
    # introduced_version is the version used for aggregation.
    introduced_version: str
    # regression_labels contains all distinct regression versions found on the issue.
    regression_labels: list[str]
    # status is the current issue status.
    status: str
    # closing_milestone is the closing GitHub milestone title when available.
    closing_milestone: str | None


@dataclass(frozen=True)
class RegressionRecord:
    """JSON-ready form of a regression issue."""

    # issue_number is the original GitHub issue number.
    issue_number: int
    # human_id is git-bug's short identifier for the issue.
    human_id: str
    # title is the issue title.
    title: str
    # status is the current issue status.
    status: str
    # url is the original GitHub issue URL.
    url: str
    # regression_labels lists all regression versions present on the issue.
    regression_labels: list[str]
    # closing_milestone is the closing milestone, when known.
    closing_milestone: str | None

    def to_json_dict(self) -> dict[str, Any]:
        """Convert the record to a JSON-serializable dictionary.

        Args:
            self: The record to serialize.

        Returns:
            A dictionary matching the JSON output schema.
        """

        data: dict[str, Any] = {
            "issue_number": self.issue_number,
            "title": self.title,
            "status": self.status,
            "url": self.url,
        }
        if self.human_id:
            data["human_id"] = self.human_id
        if self.regression_labels:
            data["regression_labels"] = self.regression_labels
        if self.closing_milestone:
            data["closing_milestone"] = self.closing_milestone
        return data


@dataclass(frozen=True)
class MilestoneInfo:
    """Metadata recorded for one milestone on the chart x-axis."""

    # version is the milestone title, which is also used as the count-matrix key.
    version: str
    # closed_on is the day on which GitHub reports the milestone as closed, when known.
    closed_on: date | None

    def to_json_dict(self) -> dict[str, Any]:
        """Convert the milestone to a JSON-serializable dictionary.

        Args:
            self: The milestone metadata to serialize.

        Returns:
            A dictionary with the milestone version and close date.
        """

        return {
            "version": self.version,
            "closed_on": self.closed_on.isoformat() if self.closed_on is not None else None,
        }

    @classmethod
    def from_json_value(cls, value: Any) -> MilestoneInfo:
        """Build a MilestoneInfo from a JSON value.

        Args:
            value: Either a milestone object from the current schema or a plain version string
                from the older schema.

        Returns:
            A typed MilestoneInfo instance.
        """

        if isinstance(value, str):
            return cls(version=value, closed_on=None)
        if not isinstance(value, Mapping):
            raise TypeError("milestone entries must be strings or objects")
        raw_closed_on: Any = value.get("closed_on")
        closed_on: date | None = None
        if raw_closed_on is not None:
            closed_on = parse_iso_date(str(raw_closed_on))
        return cls(version=str(value.get("version", "")), closed_on=closed_on)


@dataclass(frozen=True)
class RegressionsByVersionFile:
    """Payload written to `regressions-by-version.json`."""

    # versions is the global version order used by the file.
    versions: list[str]
    # regressions maps an introduced version to its regression issue records.
    regressions: dict[str, list[RegressionRecord]]
    # unclassified lists closed regressions that could not be placed on a version milestone timeline.
    unclassified: list[RegressionRecord]

    def to_json_dict(self) -> dict[str, Any]:
        """Convert the payload to a JSON-serializable dictionary.

        Args:
            self: The payload to serialize.

        Returns:
            A dictionary matching the JSON output schema.
        """

        regressions_json: dict[str, list[dict[str, Any]]] = {
            version: [record.to_json_dict() for record in records]
            for version, records in self.regressions.items()
        }
        data: dict[str, Any] = {
            "versions": self.versions,
            "regressions": regressions_json,
        }
        if self.unclassified:
            data["unclassified_closed_regressions"] = [
                record.to_json_dict() for record in self.unclassified
            ]
        return data


@dataclass(frozen=True)
class MilestoneCountsFile:
    """Payload written to the milestone-based JSON files."""

    # milestones is the ordered milestone axis used by the count matrix, including close dates.
    milestones: list[MilestoneInfo]
    # versions is the ordered introduced-version axis used by the count matrix.
    versions: list[str]
    # counts maps each milestone version to a map from introduced version to count.
    counts: dict[str, dict[str, int]]

    def to_json_dict(self) -> dict[str, Any]:
        """Convert the payload to a JSON-serializable dictionary.

        Args:
            self: The payload to serialize.

        Returns:
            A dictionary matching the JSON output schema.
        """

        return {
            "milestones": [milestone.to_json_dict() for milestone in self.milestones],
            "versions": self.versions,
            "counts": self.counts,
        }

    @classmethod
    def from_json_dict(cls, data: Mapping[str, Any]) -> MilestoneCountsFile:
        """Build a MilestoneCountsFile from decoded JSON data.

        Args:
            data: A mapping decoded from one of the milestone-based JSON files.

        Returns:
            A typed MilestoneCountsFile instance.
        """

        counts_raw: Any = data.get("counts", {})
        counts: dict[str, dict[str, int]] = {}
        milestone_key: str
        row_raw: Any
        for milestone_key, row_raw in (counts_raw or {}).items():
            row_mapping: Mapping[str, Any] = row_raw if isinstance(row_raw, Mapping) else {}
            counts[str(milestone_key)] = {
                str(version): int(value) for version, value in row_mapping.items()
            }
        milestones_raw: Any = data.get("milestones", [])
        milestones: list[MilestoneInfo] = [
            MilestoneInfo.from_json_value(value) for value in milestones_raw
        ]
        return cls(
            milestones=milestones,
            versions=[str(value) for value in data.get("versions", [])],
            counts=counts,
        )


@dataclass(frozen=True)
class GraphQLIssue:
    """Subset of GitHub GraphQL issue data needed for milestone lookup."""

    # number is the GitHub issue number.
    number: int
    # state is the GitHub issue state.
    state: str
    # milestone_title is the attached GitHub milestone title, when any.
    milestone_title: str | None


def main(argv: Sequence[str] | None = None) -> int:
    """Parse command-line arguments and execute the requested mode.

    Args:
        argv: Optional replacement for `sys.argv[1:]`.

    Returns:
        Zero on success and one on failure.
    """

    try:
        config: Config = parse_arguments(argv)
        run(config)
    except Exception as error:  # noqa: BLE001
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


def parse_arguments(argv: Sequence[str] | None) -> Config:
    """Parse command-line arguments into a typed Config value.

    Args:
        argv: Optional argument vector. When None, argparse reads from sys.argv.

    Returns:
        The parsed configuration.
    """

    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description=(
            "Extract regression data from git-bug, write JSON and markdown reports, "
            "and render SVG charts."
        )
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Path to the Git repository root that contains .git/git-bug.",
    )
    parser.add_argument(
        "--out-dir",
        default=".",
        help="Directory in which generated files are written.",
    )
    parser.add_argument(
        "--owner",
        default="agda",
        help="GitHub repository owner used for milestone lookups.",
    )
    parser.add_argument(
        "--repo",
        default="agda",
        help="GitHub repository name used for milestone lookups.",
    )
    parser.add_argument(
        "--chart-only",
        action="store_true",
        help=(
            "Regenerate regressions-open-by-version.svg and regressions-open-by-date.svg "
            "from regressions-open-by-milestone.json in --out-dir."
        ),
    )
    namespace: argparse.Namespace = parser.parse_args(argv)
    return Config(
        repo_root=Path(namespace.repo_root).resolve(),
        out_dir=Path(namespace.out_dir).resolve(),
        owner=str(namespace.owner),
        repo=str(namespace.repo),
        chart_only=bool(namespace.chart_only),
    )


def run(config: Config) -> None:
    """Execute either full report generation or chart-only regeneration.

    Args:
        config: The command-line configuration. config.out_dir must be writable.

    Returns:
        Nothing. Output files are written as a side effect.
    """

    ensure_output_directory(config.out_dir)
    if config.chart_only:
        regenerate_charts(config.out_dir)
        return

    issues: list[RegressionIssue] = load_regression_issues(config.repo_root)
    if not issues:
        raise RuntimeError("no regression issues found")

    # GitHub is needed both for issue milestones and for milestone close dates used in the
    # date-based chart.
    token: str = github_token()
    closed_issue_numbers: list[int] = [
        issue.issue_number for issue in issues if issue.status == "closed"
    ]
    closing_milestones: dict[int, str] = {}
    if closed_issue_numbers:
        closing_milestones = fetch_closing_milestones(
            owner=config.owner,
            repo=config.repo,
            token=token,
            issue_numbers=closed_issue_numbers,
        )
    milestone_close_dates: dict[str, date | None] = fetch_milestone_close_dates(
        owner=config.owner,
        repo=config.repo,
        token=token,
    )

    # Local git-bug JSON lacks closing milestones, so closed issues are enriched here before
    # any aggregate data is derived.
    enriched_issues: list[RegressionIssue] = [
        RegressionIssue(
            issue_number=issue.issue_number,
            human_id=issue.human_id,
            title=issue.title,
            url=issue.url,
            introduced_version=issue.introduced_version,
            regression_labels=issue.regression_labels,
            status=issue.status,
            closing_milestone=(
                closing_milestones.get(issue.issue_number)
                if issue.status == "closed"
                else issue.closing_milestone
            ),
        )
        for issue in issues
    ]

    version_order, milestones, unclassified_closed = collect_versions(
        issues=enriched_issues,
        milestone_close_dates=milestone_close_dates,
    )
    if not milestones:
        raise RuntimeError("no version milestones found")

    by_version: RegressionsByVersionFile = build_regressions_by_version(
        issues=enriched_issues,
        version_order=version_order,
        unclassified_closed=unclassified_closed,
    )
    closed_counts: MilestoneCountsFile = build_closed_counts(
        issues=enriched_issues,
        version_order=version_order,
        milestones=milestones,
    )
    open_counts: MilestoneCountsFile = build_open_counts(
        issues=enriched_issues,
        version_order=version_order,
        milestones=milestones,
    )
    markdown: str = markdown_table(
        version_order=version_order,
        milestones=milestones,
        open_counts=open_counts,
    )
    version_svg: str = render_version_svg(
        version_order=version_order,
        milestones=milestones,
        open_counts=open_counts,
    )
    date_svg: str = render_date_svg(
        version_order=version_order,
        milestones=milestones,
        open_counts=open_counts,
    )

    # Persist all derived artifacts with a shared version order and milestone metadata.
    write_json(config.out_dir / "regressions-by-version.json", by_version.to_json_dict())
    write_json(
        config.out_dir / "regressions-closed-by-milestone.json",
        closed_counts.to_json_dict(),
    )
    write_json(
        config.out_dir / "regressions-open-by-milestone.json",
        open_counts.to_json_dict(),
    )
    write_text(config.out_dir / "regressions-open-by-version.md", markdown)
    write_text(config.out_dir / "regressions-open-by-version.svg", version_svg)
    write_text(config.out_dir / "regressions-open-by-date.svg", date_svg)

    print(f"Wrote {config.out_dir / 'regressions-by-version.json'}")
    print(f"Wrote {config.out_dir / 'regressions-closed-by-milestone.json'}")
    print(f"Wrote {config.out_dir / 'regressions-open-by-milestone.json'}")
    print(f"Wrote {config.out_dir / 'regressions-open-by-version.md'}")
    print(f"Wrote {config.out_dir / 'regressions-open-by-version.svg'}")
    print(f"Wrote {config.out_dir / 'regressions-open-by-date.svg'}")


def ensure_output_directory(out_dir: Path) -> None:
    """Create the output directory when it does not yet exist.

    Args:
        out_dir: Directory in which output files will be written.

    Returns:
        Nothing. The directory is created if needed.
    """

    out_dir.mkdir(parents=True, exist_ok=True)


def regenerate_charts(out_dir: Path) -> None:
    """Regenerate both SVG charts from previously computed JSON data.

    Args:
        out_dir: Directory that already contains `regressions-open-by-milestone.json`.

    Returns:
        Nothing. The SVG charts are rewritten in out_dir.
    """

    open_counts_path: Path = out_dir / "regressions-open-by-milestone.json"
    open_counts: MilestoneCountsFile = MilestoneCountsFile.from_json_dict(
        read_json(open_counts_path)
    )
    version_svg: str = render_version_svg(
        version_order=open_counts.versions,
        milestones=open_counts.milestones,
        open_counts=open_counts,
    )
    date_svg: str = render_date_svg(
        version_order=open_counts.versions,
        milestones=open_counts.milestones,
        open_counts=open_counts,
    )
    version_svg_path: Path = out_dir / "regressions-open-by-version.svg"
    date_svg_path: Path = out_dir / "regressions-open-by-date.svg"
    write_text(version_svg_path, version_svg)
    write_text(date_svg_path, date_svg)
    print(f"Wrote {version_svg_path}")
    print(f"Wrote {date_svg_path}")


def load_regression_issues(repo_root: Path) -> list[RegressionIssue]:
    """Load and normalize regression issues from local git-bug bridge data.

    Args:
        repo_root: Git repository root in which `git bug bug --format json` must succeed.

    Returns:
        Regression issues sorted by introduced version and issue number.
    """

    command: list[str] = ["git", "bug", "bug", "--format", "json"]
    process: subprocess.CompletedProcess[str] = subprocess.run(
        command,
        cwd=repo_root,
        check=False,
        capture_output=True,
        text=True,
    )
    if process.returncode != 0:
        stderr: str = process.stderr.strip()
        stdout: str = process.stdout.strip()
        details: str = stderr or stdout
        raise RuntimeError(f"run `git bug bug --format json`: {details}")

    raw_data: Any = json.loads(process.stdout)
    issues: list[GitBugIssue] = [GitBugIssue.from_json_dict(item) for item in raw_data]
    result: list[RegressionIssue] = []

    for issue in issues:
        # Every regression label is preserved for traceability, but aggregation uses the
        # earliest version when more than one such label is present.
        regressions: list[str] = regression_versions(issue.labels)
        if not regressions:
            continue
        url: str = issue.metadata.get("github-url", "")
        issue_number: int = issue_number_from_url(url)
        result.append(
            RegressionIssue(
                issue_number=issue_number,
                human_id=issue.human_id,
                title=issue.title,
                url=url,
                introduced_version=regressions[0],
                regression_labels=regressions,
                status=issue.status,
                closing_milestone=None,
            )
        )

    result.sort(
        key=lambda issue: (version_sort_key(issue.introduced_version), issue.issue_number)
    )
    return result


def regression_versions(labels: Sequence[str]) -> list[str]:
    """Extract all distinct regression versions from a label list.

    Args:
        labels: Arbitrary issue labels, some of which may match `regression in VER`.

    Returns:
        Distinct regression versions sorted in semantic version order.
    """

    found: set[str] = set()
    for label in labels:
        match: re.Match[str] | None = REGRESSION_LABEL_PATTERN.fullmatch(label)
        if match is None:
            continue
        found.add(match.group(1))
    return sorted_versions(found)


def issue_number_from_url(url: str) -> int:
    """Extract the GitHub issue number from a GitHub issue URL.

    Args:
        url: A GitHub issue URL that must end in `/issues/<number>`.

    Returns:
        The parsed issue number.
    """

    match: re.Match[str] | None = GITHUB_ISSUE_URL_PATTERN.search(url)
    if match is None:
        raise ValueError(f"not a GitHub issue URL: {url!r}")
    return int(match.group(1))


def github_token() -> str:
    """Resolve a token for GitHub API access.

    Args:
        None.

    Returns:
        A GitHub token from `GITHUB_TOKEN`, `GH_TOKEN`, or `gh auth token`.
    """

    for variable in ("GITHUB_TOKEN", "GH_TOKEN"):
        token: str = os.environ.get(variable, "").strip()
        if token:
            return token

    gh_path: str | None = which("gh")
    if gh_path is not None:
        process: subprocess.CompletedProcess[str] = subprocess.run(
            [gh_path, "auth", "token"],
            check=False,
            capture_output=True,
            text=True,
        )
        if process.returncode == 0:
            token = process.stdout.strip()
            if token:
                return token

    raise RuntimeError(
        "missing GitHub token: set GITHUB_TOKEN or GH_TOKEN, or authenticate with `gh auth login`"
    )


def fetch_closing_milestones(
    owner: str,
    repo: str,
    token: str,
    issue_numbers: Sequence[int],
) -> dict[int, str]:
    """Fetch closing milestone titles for closed issues from GitHub GraphQL.

    Args:
        owner: GitHub repository owner.
        repo: GitHub repository name.
        token: GitHub API token.
        issue_numbers: GitHub issue numbers to query.

    Returns:
        A map from issue number to milestone title for issues that are closed and have one.
    """

    sorted_numbers: list[int] = sorted(issue_numbers)
    result: dict[int, str] = {}

    # Batch issue lookups so GraphQL requests remain compact while avoiding one request per issue.
    for start in range(0, len(sorted_numbers), 50):
        batch: list[int] = sorted_numbers[start : start + 50]
        query: str = milestone_query(owner=owner, repo=repo, issue_numbers=batch)
        payload: bytes = json.dumps({"query": query}).encode("utf-8")
        request: urllib.request.Request = urllib.request.Request(
            "https://api.github.com/graphql",
            data=payload,
            headers={
                "Authorization": f"bearer {token}",
                "Content-Type": "application/json",
                "Accept": "application/vnd.github+json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=30.0) as response:
                response_data: Any = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as error:
            body: str = error.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"GitHub GraphQL returned {error.code}: {body}") from error

        errors_raw: Any = response_data.get("errors", [])
        if errors_raw:
            message: str = str(errors_raw[0].get("message", "unknown GitHub GraphQL error"))
            raise RuntimeError(f"GitHub GraphQL error: {message}")

        repository_data: Mapping[str, Any] = (
            response_data.get("data", {}).get("repository", {}) or {}
        )
        parsed: dict[int, GraphQLIssue] = parse_graphql_repository(repository_data)
        for issue in parsed.values():
            if issue.state != "CLOSED" or issue.milestone_title is None:
                continue
            result[issue.number] = issue.milestone_title

    return result


def fetch_milestone_close_dates(
    owner: str,
    repo: str,
    token: str,
) -> dict[str, date | None]:
    """Fetch milestone close dates from the GitHub REST API.

    Args:
        owner: GitHub repository owner.
        repo: GitHub repository name.
        token: GitHub API token.

    Returns:
        A map from milestone title to its close date, or None when the milestone is open.
    """

    result: dict[str, date | None] = {}
    page: int = 1

    while True:
        request: urllib.request.Request = urllib.request.Request(
            f"https://api.github.com/repos/{owner}/{repo}/milestones?state=all&per_page=100&page={page}",
            headers={
                "Authorization": f"bearer {token}",
                "Accept": "application/vnd.github+json",
            },
            method="GET",
        )
        try:
            with urllib.request.urlopen(request, timeout=30.0) as response:
                page_data: Any = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as error:
            body: str = error.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"GitHub milestones returned {error.code}: {body}") from error

        if not page_data:
            break

        milestone: Any
        for milestone in page_data:
            title: str = str(milestone.get("title", "")).strip()
            closed_at_raw: Any = milestone.get("closed_at")
            closed_on: date | None = None
            if closed_at_raw is not None:
                closed_on = parse_iso_date(str(closed_at_raw)[:10])
            result[title] = closed_on
        page += 1

    return result


def parse_graphql_repository(data: Mapping[str, Any]) -> dict[int, GraphQLIssue]:
    """Parse aliased GraphQL issue lookups under a repository object.

    Args:
        data: Repository payload keyed by aliases such as `i1234`.

    Returns:
        A map from issue number to parsed GraphQL issue data.
    """

    result: dict[int, GraphQLIssue] = {}
    alias: str
    payload: Any
    for alias, payload in data.items():
        if payload is None:
            continue
        if not alias.startswith("i"):
            raise ValueError(f"unexpected GraphQL alias: {alias!r}")
        issue_number: int = int(alias[1:])
        milestone_raw: Any = payload.get("milestone")
        milestone_title: str | None = None
        if isinstance(milestone_raw, Mapping) and milestone_raw.get("title") is not None:
            milestone_title = str(milestone_raw["title"]).strip()
        result[issue_number] = GraphQLIssue(
            number=int(payload.get("number", issue_number)),
            state=str(payload.get("state", "")),
            milestone_title=milestone_title,
        )
    return result


def milestone_query(owner: str, repo: str, issue_numbers: Sequence[int]) -> str:
    """Build a GraphQL query for milestone lookup on selected issues.

    Args:
        owner: GitHub repository owner.
        repo: GitHub repository name.
        issue_numbers: GitHub issue numbers to include in the query.

    Returns:
        A complete GraphQL query string with aliased issue fields.
    """

    fields: list[str] = [
        f"i{issue_number}: issue(number: {issue_number}) {{ number state milestone {{ title }} }}"
        for issue_number in issue_numbers
    ]
    return (
        f'query {{ repository(owner: {json.dumps(owner)}, name: {json.dumps(repo)}) '
        f'{{ {" ".join(fields)} }} }}'
    )


def collect_versions(
    issues: Sequence[RegressionIssue],
    milestone_close_dates: Mapping[str, date | None],
) -> tuple[list[str], list[MilestoneInfo], list[RegressionRecord]]:
    """Derive the global version axis, milestone axis, and unclassified closed issues.

    Args:
        issues: Regression issues that already contain introduced versions and any available
            closing milestones.
        milestone_close_dates: Map from milestone version to its GitHub close date.

    Returns:
        A triple of ordered versions, ordered milestone metadata, and closed issues that could
        not be placed on a version milestone timeline.
    """

    version_set: set[str] = set()
    milestone_set: set[str] = set()
    unclassified_closed: list[RegressionRecord] = []

    issue: RegressionIssue
    for issue in issues:
        version_set.add(issue.introduced_version)
        if issue.closing_milestone is None:
            if issue.status == "closed":
                unclassified_closed.append(make_regression_record(issue))
            continue
        if not VERSION_PATTERN.fullmatch(issue.closing_milestone):
            unclassified_closed.append(make_regression_record(issue))
            continue
        milestone_set.add(issue.closing_milestone)
        version_set.add(issue.closing_milestone)

    version_order: list[str] = sorted_versions(version_set)
    milestone_versions: list[str] = sorted_versions(version_set | milestone_set)
    milestones: list[MilestoneInfo] = [
        MilestoneInfo(version=version, closed_on=milestone_close_dates.get(version))
        for version in milestone_versions
    ]
    unclassified_closed.sort(key=lambda issue: issue.issue_number)
    return version_order, milestones, unclassified_closed


def build_regressions_by_version(
    issues: Sequence[RegressionIssue],
    version_order: Sequence[str],
    unclassified_closed: Sequence[RegressionRecord],
) -> RegressionsByVersionFile:
    """Group regression issues by introduced version for JSON output.

    Args:
        issues: Regression issues to group.
        version_order: Version axis that must contain every introduced version.
        unclassified_closed: Closed issues excluded from milestone-based aggregates.

    Returns:
        The payload written to `regressions-by-version.json`.
    """

    regressions: dict[str, list[RegressionRecord]] = {version: [] for version in version_order}
    for issue in issues:
        regressions[issue.introduced_version].append(make_regression_record(issue))
    for records in regressions.values():
        records.sort(key=lambda issue: issue.issue_number)
    return RegressionsByVersionFile(
        versions=list(version_order),
        regressions=regressions,
        unclassified=list(unclassified_closed),
    )


def build_closed_counts(
    issues: Sequence[RegressionIssue],
    version_order: Sequence[str],
    milestones: Sequence[MilestoneInfo],
) -> MilestoneCountsFile:
    """Count how many regressions each milestone closed per introduced version.

    Args:
        issues: Regression issues with normalized closing milestones.
        version_order: Introduced-version axis for the output matrix.
        milestones: Milestone axis for the output matrix.

    Returns:
        The payload written to `regressions-closed-by-milestone.json`.
    """

    milestone_versions: list[str] = [milestone.version for milestone in milestones]
    counts: dict[str, dict[str, int]] = {
        milestone_version: {version: 0 for version in version_order}
        for milestone_version in milestone_versions
    }
    for issue in issues:
        if issue.status != "closed" or issue.closing_milestone is None:
            continue
        if not VERSION_PATTERN.fullmatch(issue.closing_milestone):
            continue
        counts[issue.closing_milestone][issue.introduced_version] += 1
    return MilestoneCountsFile(
        milestones=list(milestones),
        versions=list(version_order),
        counts=counts,
    )


def build_open_counts(
    issues: Sequence[RegressionIssue],
    version_order: Sequence[str],
    milestones: Sequence[MilestoneInfo],
) -> MilestoneCountsFile:
    """Count how many regressions are still open at each milestone.

    Args:
        issues: Regression issues with normalized introduced versions and closing milestones.
        version_order: Introduced-version axis for the output matrix.
        milestones: Milestone axis for the output matrix.

    Returns:
        The payload written to `regressions-open-by-milestone.json`.
    """

    counts: dict[str, dict[str, int]] = {}
    milestone: MilestoneInfo
    for milestone in milestones:
        row: dict[str, int] = {}
        version: str
        for version in version_order:
            if compare_version(version, milestone.version) > 0:
                break
            row[version] = 0
        counts[milestone.version] = row

    for milestone in milestones:
        row: dict[str, int] = counts[milestone.version]
        issue: RegressionIssue
        for issue in issues:
            # Closed issues without a usable version milestone are surfaced in the per-issue JSON
            # but intentionally omitted from the milestone timeline.
            if issue.status == "closed" and not is_version_string(issue.closing_milestone):
                continue
            if compare_version(issue.introduced_version, milestone.version) > 0:
                continue
            if (
                issue.status == "closed"
                and issue.closing_milestone is not None
                and compare_version(issue.closing_milestone, milestone.version) <= 0
            ):
                continue
            row[issue.introduced_version] += 1

    return MilestoneCountsFile(
        milestones=list(milestones),
        versions=list(version_order),
        counts=counts,
    )


def make_regression_record(issue: RegressionIssue) -> RegressionRecord:
    """Convert an internal RegressionIssue to its JSON-ready form.

    Args:
        issue: The normalized regression issue to convert.

    Returns:
        A RegressionRecord that preserves all traceability fields.
    """

    return RegressionRecord(
        issue_number=issue.issue_number,
        human_id=issue.human_id,
        title=issue.title,
        status=issue.status,
        url=issue.url,
        regression_labels=list(issue.regression_labels),
        closing_milestone=issue.closing_milestone,
    )


def sorted_versions(versions: set[str]) -> list[str]:
    """Sort a set of dotted numeric versions in semantic version order.

    Args:
        versions: Version strings of the form `N(.N)*`.

    Returns:
        A newly allocated sorted list.
    """

    return sorted(versions, key=version_sort_key)


def version_sort_key(version: str) -> tuple[int, ...]:
    """Compute a semantic sort key for a dotted numeric version string.

    Args:
        version: A dotted numeric version string.

    Returns:
        A tuple of integers suitable for semantic version ordering.
    """

    return tuple(parse_version(version))


def compare_version(left: str, right: str) -> int:
    """Compare two dotted numeric version strings.

    Args:
        left: Left-hand version string.
        right: Right-hand version string.

    Returns:
        -1 when left < right, 0 when left == right, and 1 when left > right.
    """

    left_parts: list[int] = parse_version(left)
    right_parts: list[int] = parse_version(right)
    max_length: int = max(len(left_parts), len(right_parts))
    index: int
    for index in range(max_length):
        left_value: int = left_parts[index] if index < len(left_parts) else 0
        right_value: int = right_parts[index] if index < len(right_parts) else 0
        if left_value < right_value:
            return -1
        if left_value > right_value:
            return 1
    return 0


def parse_version(version: str | None) -> list[int]:
    """Split a dotted numeric version string into integer components.

    Args:
        version: Version string of the form `N(.N)*`.

    Returns:
        The parsed integer components.
    """

    if version is None or not version:
        return [0]
    parts: list[str] = version.split(".")
    try:
        return [int(part) for part in parts]
    except ValueError as error:
        raise ValueError(f"invalid version string: {version!r}") from error


def is_version_string(value: str | None) -> bool:
    """Check whether a string looks like a dotted numeric version.

    Args:
        value: The string to test.

    Returns:
        True when value matches the accepted version syntax.
    """

    return value is not None and VERSION_PATTERN.fullmatch(value) is not None


def parse_iso_date(value: str) -> date:
    """Parse an ISO `YYYY-MM-DD` date string.

    Args:
        value: Date string in ISO calendar format.

    Returns:
        The parsed date value.
    """

    return date.fromisoformat(value)


def markdown_table(
    version_order: Sequence[str],
    milestones: Sequence[MilestoneInfo],
    open_counts: MilestoneCountsFile,
) -> str:
    """Render the open-count matrix as a markdown table.

    Args:
        version_order: Introduced-version axis for the matrix.
        milestones: Milestone axis for the matrix.
        open_counts: Open-count payload matching the given axes.

    Returns:
        A complete markdown document string.
    """

    headers: list[str] = ["", *version_order, "Total"]
    rows: list[list[str]] = [headers, ["---"] * len(headers)]

    milestone: MilestoneInfo
    for milestone in milestones:
        row: list[str] = [milestone.version]
        total: int = 0
        version: str
        for version in version_order:
            if compare_version(version, milestone.version) > 0:
                row.append("")
                continue
            value: int = open_counts.counts[milestone.version][version]
            total += value
            row.append(str(value))
        row.append(str(total))
        rows.append(row)

    widths: list[int] = [0] * len(headers)
    row: list[str]
    for row in rows:
        index: int
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(cell))

    lines: list[str] = ["Open regressions per version", ""]
    row_index: int
    for row_index, row in enumerate(rows):
        padded_cells: list[str] = []
        index = 0
        for index, cell in enumerate(row):
            numeric: bool = row_index > 1 and index > 0
            padded_cells.append(pad_cell(value=cell, width=widths[index], numeric=numeric))
        lines.append("| " + " | ".join(padded_cells) + " |")
    return "\n".join(lines) + "\n"


def pad_cell(value: str, width: int, numeric: bool) -> str:
    """Pad a markdown table cell to a fixed width.

    Args:
        value: Cell text to align.
        width: Target cell width, which must be at least len(value).
        numeric: Whether the cell should be right-aligned.

    Returns:
        The padded cell text.
    """

    if numeric and value:
        return value.rjust(width)
    return value.ljust(width)


def render_version_svg(
    version_order: Sequence[str],
    milestones: Sequence[MilestoneInfo],
    open_counts: MilestoneCountsFile,
) -> str:
    """Render the open-count matrix as a stacked SVG bar chart with uniform spacing.

    Args:
        version_order: Introduced-version axis for the matrix.
        milestones: Milestone axis for the matrix.
        open_counts: Open-count payload matching the given axes.

    Returns:
        A self-contained SVG document.
    """

    milestone_versions: list[str] = [milestone.version for milestone in milestones]
    totals: dict[str, int] = total_counts(
        version_order=version_order,
        milestone_versions=milestone_versions,
        open_counts=open_counts,
    )
    max_total: int = max(totals.values(), default=1)
    if max_total == 0:
        max_total = 1

    top_margin: int = 40
    left_margin: int = 70
    bottom_margin: int = 140
    plot_height: int = 420
    legend_columns: int = 1 if len(version_order) <= 24 else math.ceil(len(version_order) / 24.0)
    legend_column_width: int = 130
    legend_width: int = legend_columns * legend_column_width + 20
    plot_width: int = max(840, len(milestone_versions) * 40)
    width: int = left_margin + plot_width + legend_width
    height: int = top_margin + plot_height + bottom_margin
    plot_bottom: int = top_margin + plot_height
    plot_right: int = left_margin + plot_width

    slot_width: float = plot_width / max(len(milestone_versions), 1)
    bar_width: float = uniform_bar_width(slot_width)
    scale: float = plot_height / float(max_total)
    tick_step: int = nice_step(max_total)
    color_by_version: dict[str, str] = colors_by_version(version_order)

    lines: list[str] = svg_header(
        width=width,
        height=height,
        title="Open regressions by introduced version",
    )
    lines.extend(horizontal_grid_lines(left_margin, plot_right, plot_bottom, scale, max_total, tick_step))
    lines.extend(axis_lines(left_margin, plot_right, plot_bottom, top_margin))

    # Draw each bar from bottom to top in version order so that each version keeps a stable
    # color across milestones.
    milestone_index: int
    milestone: MilestoneInfo
    for milestone_index, milestone in enumerate(milestones):
        center_x: float = left_margin + slot_width * (milestone_index + 0.5)
        x: float = center_x - bar_width / 2.0
        current_y: float = float(plot_bottom)
        version: str
        for version in version_order:
            if compare_version(version, milestone.version) > 0:
                break
            value: int = open_counts.counts[milestone.version].get(version, 0)
            if value == 0:
                continue
            segment_height: float = value * scale
            current_y -= segment_height
            lines.append(
                f'<rect class="bar" x="{x:.2f}" y="{current_y:.2f}" width="{bar_width:.2f}" '
                f'height="{segment_height:.2f}" fill="{color_by_version[version]}"/>'
            )
        lines.append(
            f'<text class="tick" transform="translate({center_x - bar_width / 2.0:.2f},'
            f'{plot_bottom + 18}) rotate(45)" text-anchor="start">'
            f"{html.escape(milestone.version)}</text>"
        )

    lines.append(y_axis_label(top_margin=top_margin, plot_height=plot_height))
    lines.extend(
        legend_lines(
            version_order=version_order,
            color_by_version=color_by_version,
            legend_x=plot_right + 28,
            legend_top=top_margin + 10,
            reverse=True,
        )
    )
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def render_date_svg(
    version_order: Sequence[str],
    milestones: Sequence[MilestoneInfo],
    open_counts: MilestoneCountsFile,
) -> str:
    """Render the open-count matrix as a stacked SVG chart positioned by close date.

    Args:
        version_order: Introduced-version axis for the matrix.
        milestones: Milestone axis for the matrix, including close dates.
        open_counts: Open-count payload matching the given axes.

    Returns:
        A self-contained SVG document.
    """

    dated_milestones: list[MilestoneInfo] = [
        milestone for milestone in milestones if milestone.closed_on is not None
    ]
    if not dated_milestones:
        return empty_svg("Open regressions by milestone close date", "No milestone close dates available")

    milestone_versions: list[str] = [milestone.version for milestone in dated_milestones]
    totals: dict[str, int] = total_counts(
        version_order=version_order,
        milestone_versions=milestone_versions,
        open_counts=open_counts,
    )
    max_total: int = max(totals.values(), default=1)
    if max_total == 0:
        max_total = 1

    min_closed_on: date = min(milestone.closed_on for milestone in dated_milestones if milestone.closed_on is not None)
    max_closed_on: date = max(milestone.closed_on for milestone in dated_milestones if milestone.closed_on is not None)
    axis_start: date = date(min_closed_on.year, 1, 1)
    axis_end: date = date(max_closed_on.year + 1, 1, 1)
    span_days: int = max((axis_end - axis_start).days, 1)

    top_margin: int = 40
    left_margin: int = 70
    bottom_margin: int = 90
    plot_height: int = 420
    legend_columns: int = 1 if len(version_order) <= 24 else math.ceil(len(version_order) / 24.0)
    legend_column_width: int = 130
    legend_width: int = legend_columns * legend_column_width + 20
    year_span: int = axis_end.year - axis_start.year
    plot_width: int = max(840, year_span * 90)
    width: int = left_margin + plot_width + legend_width
    height: int = top_margin + plot_height + bottom_margin
    plot_bottom: int = top_margin + plot_height
    plot_right: int = left_margin + plot_width

    uniform_slot_width: float = max(840, len(milestones) * 30) / max(len(milestones), 1)
    bar_width: float = uniform_bar_width(uniform_slot_width)
    scale: float = plot_height / float(max_total)
    tick_step: int = nice_step(max_total)
    color_by_version: dict[str, str] = colors_by_version(version_order)

    lines: list[str] = svg_header(
        width=width,
        height=height,
        title="Open regressions by milestone close date",
    )
    lines.extend(horizontal_grid_lines(left_margin, plot_right, plot_bottom, scale, max_total, tick_step))

    year: int
    for year in range(axis_start.year, axis_end.year + 1):
        year_start: date = date(year, 1, 1)
        x: float = left_margin + plot_width * ((year_start - axis_start).days / span_days)
        if x > plot_right + 0.5:
            continue
        lines.append(
            f'<line class="grid" x1="{x:.2f}" y1="{top_margin}" x2="{x:.2f}" y2="{plot_bottom}"/>'
        )
        lines.append(
            f'<text class="tick" x="{x:.2f}" y="{plot_bottom + 20}" text-anchor="middle">{year}</text>'
        )

    lines.extend(axis_lines(left_margin, plot_right, plot_bottom, top_margin))

    # Draw bars at the actual close dates of milestones instead of giving each milestone an
    # equal-width slot on the x-axis.
    milestone: MilestoneInfo
    for milestone in dated_milestones:
        closed_on: date = milestone.closed_on if milestone.closed_on is not None else axis_start
        x_center: float = left_margin + plot_width * ((closed_on - axis_start).days / span_days)
        x: float = x_center - bar_width / 2.0
        current_y: float = float(plot_bottom)
        version: str
        for version in version_order:
            if compare_version(version, milestone.version) > 0:
                break
            value: int = open_counts.counts[milestone.version].get(version, 0)
            if value == 0:
                continue
            segment_height: float = value * scale
            current_y -= segment_height
            lines.append(
                f'<rect class="bar" x="{x:.2f}" y="{current_y:.2f}" width="{bar_width:.2f}" '
                f'height="{segment_height:.2f}" fill="{color_by_version[version]}"/>'
            )

    lines.append(y_axis_label(top_margin=top_margin, plot_height=plot_height))
    lines.extend(
        legend_lines(
            version_order=version_order,
            color_by_version=color_by_version,
            legend_x=plot_right + 28,
            legend_top=top_margin + 10,
            reverse=True,
        )
    )
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def total_counts(
    version_order: Sequence[str],
    milestone_versions: Sequence[str],
    open_counts: MilestoneCountsFile,
) -> dict[str, int]:
    """Compute the total open regressions per milestone.

    Args:
        version_order: Introduced-version axis for the matrix.
        milestone_versions: Milestone versions whose rows should be totaled.
        open_counts: Open-count payload to aggregate.

    Returns:
        A map from milestone version to total count across all versions.
    """

    return {
        milestone_version: sum(
            open_counts.counts[milestone_version].get(version, 0) for version in version_order
        )
        for milestone_version in milestone_versions
    }


def colors_by_version(version_order: Sequence[str]) -> dict[str, str]:
    """Assign a stable chart color to each introduced version.

    Args:
        version_order: Versions in the order used by the chart and legend.

    Returns:
        A map from version string to CSS color.
    """

    return {
        version: VERSION_COLORS[index % len(VERSION_COLORS)]
        for index, version in enumerate(version_order)
    }


def uniform_bar_width(slot_width: float) -> float:
    """Compute the updated bar width from a uniform chart slot width.

    Args:
        slot_width: Width of one milestone slot in the uniformly spaced chart.

    Returns:
        The chart bar width.
    """

    return slot_width * 0.72


def svg_header(width: int, height: int, title: str) -> list[str]:
    """Build the common SVG header and stylesheet lines.

    Args:
        width: SVG viewport width in pixels.
        height: SVG viewport height in pixels.
        title: Chart title text.

    Returns:
        SVG lines containing the opening tag, stylesheet, and title.
    """

    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">',
        "<style>",
        "text{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;fill:#222}",
        ".axis{stroke:#444;stroke-width:1}",
        ".grid{stroke:#ddd;stroke-width:1}",
        ".bar{stroke:#fff;stroke-width:1}",
        ".tick{font-size:11px}",
        ".label{font-size:12px}",
        ".title{font-size:18px;font-weight:600}",
        "</style>",
        f'<text class="title" x="70" y="26">{html.escape(title)}</text>',
    ]


def horizontal_grid_lines(
    left_margin: int,
    plot_right: int,
    plot_bottom: int,
    scale: float,
    max_total: int,
    tick_step: int,
) -> list[str]:
    """Build horizontal grid and y-axis tick-label lines.

    Args:
        left_margin: Left edge of the plotting area.
        plot_right: Right edge of the plotting area.
        plot_bottom: Bottom y-coordinate of the plotting area.
        scale: Pixel height per unit count.
        max_total: Largest y-axis value.
        tick_step: Increment between y-axis ticks.

    Returns:
        SVG lines for horizontal grid lines and numeric y-axis labels.
    """

    lines: list[str] = []
    tick: int
    for tick in range(0, max_total + 1, tick_step):
        y: int = plot_bottom - round(tick * scale)
        lines.append(
            f'<line class="grid" x1="{left_margin}" y1="{y}" x2="{plot_right}" y2="{y}"/>'
        )
        lines.append(
            f'<text class="tick" x="{left_margin - 8}" y="{y}" text-anchor="end" '
            f'dominant-baseline="middle">{tick}</text>'
        )
    return lines


def axis_lines(left_margin: int, plot_right: int, plot_bottom: int, top_margin: int) -> list[str]:
    """Build the common x- and y-axis lines.

    Args:
        left_margin: Left edge of the plotting area.
        plot_right: Right edge of the plotting area.
        plot_bottom: Bottom y-coordinate of the plotting area.
        top_margin: Top y-coordinate of the plotting area.

    Returns:
        SVG lines for the x- and y-axes.
    """

    return [
        f'<line class="axis" x1="{left_margin}" y1="{plot_bottom}" x2="{plot_right}" y2="{plot_bottom}"/>',
        f'<line class="axis" x1="{left_margin}" y1="{top_margin}" x2="{left_margin}" y2="{plot_bottom}"/>',
    ]


def y_axis_label(top_margin: int, plot_height: int) -> str:
    """Build the vertical y-axis label.

    Args:
        top_margin: Top y-coordinate of the plotting area.
        plot_height: Plot height in pixels.

    Returns:
        An SVG text element for the y-axis label.
    """

    y_center: int = top_margin + plot_height // 2
    return (
        f'<text class="label" x="22" y="{y_center}" text-anchor="middle" '
        f'transform="rotate(-90 22 {y_center})">Open regressions</text>'
    )


def legend_lines(
    version_order: Sequence[str],
    color_by_version: Mapping[str, str],
    legend_x: int,
    legend_top: int,
    reverse: bool,
) -> list[str]:
    """Build the legend lines for one chart.

    Args:
        version_order: Versions to show in the legend.
        color_by_version: Mapping from version to chart color.
        legend_x: Left x-coordinate of the legend area.
        legend_top: Top y-coordinate of the legend area.
        reverse: Whether the legend should list the latest version first.

    Returns:
        SVG lines for colored legend swatches and labels.
    """

    ordered_versions: list[str] = list(reversed(version_order)) if reverse else list(version_order)
    lines: list[str] = []
    legend_index: int
    version: str
    for legend_index, version in enumerate(ordered_versions):
        column: int = legend_index // 24
        row: int = legend_index % 24
        x: int = legend_x + column * 130
        y: int = legend_top + row * 18
        lines.append(
            f'<rect x="{x}" y="{y - 10}" width="12" height="12" '
            f'fill="{color_by_version[version]}" stroke="#fff"/>'
        )
        lines.append(
            f'<text class="label" x="{x + 18}" y="{y}">{html.escape(version)}</text>'
        )
    return lines


def empty_svg(title: str, message: str) -> str:
    """Build a small SVG containing only a title and message.

    Args:
        title: Chart title text.
        message: Message shown in the plot area.

    Returns:
        A self-contained fallback SVG document.
    """

    lines: list[str] = svg_header(width=900, height=200, title=title)
    lines.append(f'<text class="label" x="70" y="100">{html.escape(message)}</text>')
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def nice_step(max_value: int) -> int:
    """Choose a readable y-axis tick step for values up to max_value.

    Args:
        max_value: Largest plotted y-axis value.

    Returns:
        A step of the form 1/2/5 * 10^k.
    """

    if max_value <= 5:
        return 1
    raw: float = max_value / 6.0
    magnitude: float = 10 ** math.floor(math.log10(raw))
    candidate: float
    for candidate in (1.0, 2.0, 5.0, 10.0):
        step: float = candidate * magnitude
        if raw <= step:
            return int(step)
    return int(10 * magnitude)


def read_json(path: Path) -> Mapping[str, Any]:
    """Read a JSON object from disk.

    Args:
        path: File path to read.

    Returns:
        The decoded JSON object.
    """

    with path.open("r", encoding="utf-8") as handle:
        data: Any = json.load(handle)
    if not isinstance(data, Mapping):
        raise TypeError(f"expected JSON object in {path}")
    return data


def write_json(path: Path, value: Mapping[str, Any]) -> None:
    """Write a JSON object to disk with stable indentation.

    Args:
        path: File path to create or overwrite.
        value: JSON-serializable mapping to write.

    Returns:
        Nothing. The file is written as a side effect.
    """

    with path.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, indent=2, sort_keys=False)
        handle.write("\n")


def write_text(path: Path, content: str) -> None:
    """Write UTF-8 text to disk.

    Args:
        path: File path to create or overwrite.
        content: Text content to write.

    Returns:
        Nothing. The file is written as a side effect.
    """

    path.write_text(content, encoding="utf-8")


def which(command: str) -> str | None:
    """Resolve a command on PATH.

    Args:
        command: Executable name to locate.

    Returns:
        The resolved executable path, or None when it is not found.
    """

    return shutil.which(command)


if __name__ == "__main__":
    sys.exit(main())
